---
title: "3 Linear Regression"
author: "nobuo"
date: "2021/3/29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Linear Regression

## Lab

Install ISLR.

```{r}
library(MASS)
library(ISLR)
```

### Simple Linear Regression

```{r}
names(Boston)
fit <- lm(medv ~ lstat, data = Boston)
fit
```
Summary of the fit.

```{r}
summary(fit)
```
```{r}
names(fit)
coef(fit)
confint(fit)
```
Prediction
```{r}
predict(fit, data.frame(lstat = c(5, 10, 15)), interval = "confidence")
predict(fit, data.frame(lstat = c(5, 10, 15)), interval = "prediction")
```
```{r}
plot(Boston$lstat, Boston$medv)
abline(fit)
```
diagnostic plots
```{r}
par(mfrow = c(2, 2))
plot(fit)
```

```{r}
plot(predict(fit), rstudent (fit))
```

```{r}
plot(hatvalues(fit))
which.max(hatvalues(fit))
```

### Multiple Linear Regression

```{r}
fit <- lm(medv ~ lstat + age, data = Boston)
summary(fit)
```
```{r}
fit <- lm(medv ~ ., data = Boston)
summary(fit)
```

```{r}
library(car)
vif(fit)
```
```{r}
fit1 <- lm(medv ~ . - age, data = Boston)
summary(fit1)
```

```{r}
summary(lm(medv ~ lstat * age, data = Boston))
```

### Non-linear Transformations of the Predictors
```{r}
fit2 <- lm(medv ~ lstat + I(lstat^2), data = Boston)
summary(fit2)
```
```{r}
fit <- lm(medv ~ lstat, data = Boston)
anova(fit, fit2)
```

```{r}
par(mfrow = c(2,2))
plot(fit2)
```


```{r}
fit5 <- lm(medv ~ poly(lstat, 5), data = Boston)
summary(fit5)
```
###  Qualitative Predictors


